[licenses]
unlicensed = "deny"
copyleft = "deny"
confidence-threshold = 0.925
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "Unlicense",
]

[advisories]
vulnerability = "warn"
unmaintained = "warn"
notice = "deny"

ignore = []