name: "ci"
on:
  pull_request:
  push:
    branches:
      - master
      - main
      - staging # for Bors
      - trying # for Bors
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable, beta, nightly, macos, win-gnu, win-msvc]
        include:
          - build: stable
            os: ubuntu-latest
            rust: stable

          - build: beta
            os: ubuntu-latest
            rust: beta

          - build: nightly
            os: ubuntu-latest
            rust: nightly

          - build: macos
            os: macOS-latest
            rust: stable

          - build: win-gnu
            os: windows-latest
            rust: stable-x86_64-gnu

          - build: win-msvc
            os: windows-latest
            rust: stable

    steps:
      - name: checkout_repository
        uses: actions/checkout@v2

      - name: install_rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal

      - name: run_build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all

      - name: run_test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v2

      - name: install_rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - name: run_clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args:  --tests -- -Dclippy::all

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v2

      - name: install_rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt

      - name: run_fmt_check
        run: |
          cargo fmt --all -- --check

  cargo_deny:
    name: cargo_deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1

  msrv:
    name: msrv
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: install_rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: install_cargo_msrv
        run: cargo install cargo-msrv
      - name: version_of_cargo_msrv
        run: cargo msrv --version # as of writing: 0.7.0
      - name: run_cargo_msrv
        run: cargo msrv --verify --ignore-lockfile --output-format json